<?php
/**
 * LOCAL DEV ROUTER — PHP built-in server only
 * Missing images/assets → proxy from live tribalsand.com
 */
$uri  = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$file = __DIR__ . $uri;

// Dynamic sitemap: /sitemap.xml is generated by sitemap.php (mirrors .htaccess)
if ($uri === '/sitemap.xml') { require __DIR__ . '/sitemap.php'; exit; }

// Serve existing files normally (PHP, CSS, JS, actual local images)
if ($uri !== '/' && file_exists($file) && !is_dir($file)) {
    return false;
}

// Strip-.php emulation: live server serves /foo from foo.php — do the same locally
if ($uri !== '/' && file_exists($file . '.php') && pathinfo($uri, PATHINFO_EXTENSION) === '') {
    $_SERVER['SCRIPT_FILENAME'] = $file . '.php';
    include $file . '.php';
    exit;
}

// Missing images/assets.
// Default: redirect to live site so local pages look real.
// Drop an empty `.router-fast` file in the project root (local screenshot/testing)
// to instead serve an instant 1×1 placeholder — avoids dozens of slow external
// image requests that stall headless renders. The sentinel is gitignored.
$imageExts = ['jpg','jpeg','png','gif','webp','svg','ico','woff','woff2','pdf','mp4','mp3'];
$ext = strtolower(pathinfo($uri, PATHINFO_EXTENSION));
if (in_array($ext, $imageExts)) {
    if (file_exists(__DIR__ . '/.router-fast')) {
        // 1×1 transparent GIF
        header('Content-Type: image/gif');
        echo base64_decode('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7');
        exit;
    }
    header('Location: https://tribalsand.com' . $uri, true, 302);
    exit;
}

// For PHP pages / directories, fall through to normal routing
return false;
